default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pg_test_development
  username: postgres
  password: postgres
  port: 5432

test:
  <<: *default
  database: pg_test_test

production:
  <<: *default
  database: articles
  username: postgres
  password: postgres

