default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: pg_test_development

test:
  <<: *default
  database: pg_test_test

production:
  <<: *default
  database: articles
